#!/bin/bash

#if [[ $# -gt 4 ]] || [[ $# -lt 4 ]]; then
#    echo "ERROR: incorrect command line"
#    exit 1
#else
#    if [[ "$1" == "-f" ]] && [[ "$3" == "-f" ]]; then
#        if [[ -z "$2" ]] || [[ -z "$4" ]]; then
#            echo "ERROR: incorrect command line"
#            exit 1
#        else
#            file1="$2"
#            file2="$4"
#            if [[ ${#file1} -le 4 ]] || [[ ${#file2} -le 4 ]]; then
#                echo "ERROR: incorrect command line"
#                exit 1
#            elif [[ ${file1: -4} != ".wav" ]] || [[ ${file2: -4} != ".wav" ]]; then
#                echo "ERROR: incorrect command line"
#                exit 1
#            fi
#        fi
#    else
#        echo "ERROR: incorrect command line"
#        exit 1
#    fi
#fi

# clearing old tmp files
rm -rf /tmp/dam-mmn/
# create directory to hold tmp files
mkdir /tmp/dam-mmn
mkdir /tmp/dam-mmn/1
mkdir /tmp/dam-mmn/2
# execute java program
java -cp out dam $@
exitVal=`echo $?`
# clear out all tmp files
rm -rf /tmp/dam-mmn/
exit $exitVal
