#!/bin/bash

#if [[ $# -gt 4 ]] || [[ $# -lt 4 ]]; then
#    echo "ERROR: incorrect command line"
#    exit 1
#else
#    if [[ "$1" == "-f" ]] && [[ "$3" == "-f" ]]; then
#        if [[ -z "$2" ]] || [[ -z "$4" ]]; then
#            echo "ERROR: incorrect command line"
#            exit 1
#        else
#            file1="$2"
#            file2="$4"
#            if [[ ${#file1} -le 4 ]] || [[ ${#file2} -le 4 ]]; then
#                echo "ERROR: incorrect command line"
#                exit 1
#            elif [[ ${file1: -4} != ".wav" ]] || [[ ${file2: -4} != ".wav" ]]; then
#                echo "ERROR: incorrect command line"
#                exit 1
#            fi
#        fi
#    else
#        echo "ERROR: incorrect command line"
#        exit 1
#    fi
#fi

java -cp out dam $@