#!/bin/bash

# detect audio misappropriations - Prototype


echo "./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D4"
./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D4
echo "./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D5"
./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D5
echo "./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D6"
./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D6
echo "./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D7"
./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D7
echo "./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D8"
./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D8
echo "./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D9"
./dam -d /home/naren90/Public/D1 -d /home/naren90/Public/D9
echo "./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D5"
./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D5
echo "./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D6"
./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D6
echo "./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D7"
./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D7
echo "./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D8"
./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D8
echo "./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D9"
./dam -d /home/naren90/Public/D4 -d /home/naren90/Public/D9
echo "./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D6"
./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D6
echo "./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D7"
./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D7
echo "./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D8"
./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D8
echo "./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D9"
./dam -d /home/naren90/Public/D5 -d /home/naren90/Public/D9
echo "./dam -d /home/naren90/Public/D6 -d /home/naren90/Public/D7"
./dam -d /home/naren90/Public/D6 -d /home/naren90/Public/D7
echo "./dam -d /home/naren90/Public/D6 -d /home/naren90/Public/D8"
./dam -d /home/naren90/Public/D6 -d /home/naren90/Public/D8
echo "./dam -d /home/naren90/Public/D6 -d /home/naren90/Public/D9"
./dam -d /home/naren90/Public/D6 -d /home/naren90/Public/D9
echo "./dam -d /home/naren90/Public/D7 -d /home/naren90/Public/D8"
./dam -d /home/naren90/Public/D7 -d /home/naren90/Public/D8
echo "./dam -d /home/naren90/Public/D7 -d /home/naren90/Public/D9"
./dam -d /home/naren90/Public/D7 -d /home/naren90/Public/D9
echo "./dam -d /home/naren90/Public/D8 -d /home/naren90/Public/D9"
./dam -d /home/naren90/Public/D8 -d /home/naren90/Public/D9

echo "./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D2"
./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D2
echo "./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D3"
./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D3
echo "./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D4"
./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D4
echo "./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D5"
./dam -d /course/cs4500f14/Assignments/A6/D1 -d /course/cs4500f14/Assignments/A6/D5
echo "./dam -d /course/cs4500f14/Assignments/A6/D2 -d /course/cs4500f14/Assignments/A6/D3"
./dam -d /course/cs4500f14/Assignments/A6/D2 -d /course/cs4500f14/Assignments/A6/D3
echo "./dam -d /course/cs4500f14/Assignments/A6/D2 -d /course/cs4500f14/Assignments/A6/D4"
./dam -d /course/cs4500f14/Assignments/A6/D2 -d /course/cs4500f14/Assignments/A6/D4
echo "./dam -d /course/cs4500f14/Assignments/A6/D2 -d /course/cs4500f14/Assignments/A6/D5"
./dam -d /course/cs4500f14/Assignments/A6/D2 -d /course/cs4500f14/Assignments/A6/D5
echo "./dam -d /course/cs4500f14/Assignments/A6/D3 -d /course/cs4500f14/Assignments/A6/D4"
./dam -d /course/cs4500f14/Assignments/A6/D3 -d /course/cs4500f14/Assignments/A6/D4
echo "./dam -d /course/cs4500f14/Assignments/A6/D3 -d /course/cs4500f14/Assignments/A6/D5"
./dam -d /course/cs4500f14/Assignments/A6/D3 -d /course/cs4500f14/Assignments/A6/D5
echo "./dam -d /course/cs4500f14/Assignments/A6/D4 -d /course/cs4500f14/Assignments/A6/D5"
./dam -d /course/cs4500f14/Assignments/A6/D4 -d /course/cs4500f14/Assignments/A6/D5
echo "./dam -d /home/naren90/Public/DMix -d /home/naren90/Public/DMix"
./dam -d /home/naren90/Public/DMix -d /home/naren90/Public/DMix